# Generated by Django 3.1.1 on 2022-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putroom',
            name='owneremail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='putroom',
            name='ownername',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='putroom',
            name='ownerphone',
            field=models.IntegerField(),
        ),
    ]
