# Generated by Django 3.1.1 on 2022-02-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20220225_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putroom',
            name='ownerphone',
            field=models.IntegerField(null=True),
        ),
    ]
