# Generated by Django 3.1.1 on 2022-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20220225_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putroom',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
